import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body className="min-h-screen flex flex-col bg-gray-100">
				<div className="self-start w-full p-4">
					<Link href="/pessoa" className="hover:underline hover:text-blue-400">
						Pessoa
					</Link>{" "}
					|{" "}
					<Link href="/conta" className="hover:underline hover:text-blue-400">
						Conta
					</Link>{" "}
					|{" "}
					<Link href="/movimentacao" className="hover:underline hover:text-blue-400">
						Movimentação
					</Link>
				</div>

				<div className="flex-grow flex items-center justify-center">
					<main className="w-full max-w-4xl p-4 bg-white shadow-md rounded-2xl">
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
